config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :rooms, only: [:create, :destroy] do
    resources :memos, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
    belongs_to :room
    belongs_to :user

    validates :text, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :room_users
    has_many :users, through: :room_users
    has_many :memos

    validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
    belongs_to :room
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :memos

  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々]+\z/, message: '全角文字を使用してください' } do
    validates :first_name
    validates :last_name
  end

  with_options presence: true, format: { with: /\A[ァ-ヶ一-]+\z/, message: '全角カナを使用してください' } do
    validates :first_name_kana
    validates :last_name_kana
  end

  validates :password, presence: true, length: { minimum: 6 },
            format: { with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]{6,}/, message: 'は半角英数字で入力してください' }

  with_options presence: true do
    validates :nickname
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, 
                                        keys: [:nickname, :first_name, :last_name, :first_name_kana, :last_name_kana])
    end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :room_create, only: [:index, :create]
  before_action :set_room, only: :index

  def index
    @memo = Memo.new
    @room = Room.find(params[:room_id])
    @memos = @room.memos.includes(:user)
  end
  
  def create
    # @room = Room.create(room_params)
    # @memo = Memo.all.order(id: "DESC")
    @room = Room.find(params[:room_id])
    @memo = @room.memos.new(memo_params)
    @memo.save
  end

  private
  def memo_params
    params.require(:memo).permit(:content).merge(user_id: current_user.id)
  end

  def room_create
    @rooms = Room.all
  end

  def set_room
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    def index
        @memo = Memo.new
        @room = Room.new
        @rooms = Room.all
    end
    
    
    def create
        @room = Room.create(room_params)
        @room.users = [current_user]
        @rooms = Room.all.order(id: "DESC")
    end

    def destroy
        room = Room.find(params[:id])
        room.destroy
        redirect_to root_path
    end
    
    private
    def room_params
        params.require(:room).permit(:name, user_ids: [current_user.id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memosuke33478</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/_form_memo.html.erb
    
    <%= form_with(model: [@room, @memo], id: "memo-form") do |form| %>
        <div class="form">
            <%= form.text_field :content, id: "content" %>
            <%= form.submit '保存', id: "submit" %>
        </div>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
    <% end %>

app/views/memos/_left_side_bar.html.erb
<%
=begin%>
 <div class="rooms">
    <div class="add-btn">
        <%= link_to new_room_path do %>
        <span class='material-icons'>add</span>
        <% end %>
    </div>
</div> 
<%
=end%>

<%
=begin%>
 <div class="rooms">
  <div id="room-form">
    <%= render partial: 'rooms/form', locals: { room: @room } %>
  </div>

  <div class="room">
    <div id="room">
      <%= render "rooms/room", {rooms: @rooms} %>
    </div>  
  </div>
</div> 
<%
=end%>


<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.name, edit_user_path(current_user) %>
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/memos/_main_memo.html.erb
<div class="memo-area">
    <div class="box25">
        <p>現在オリジナルを作成中．．．</p>
    </div>
</div>

<div class="form-space">
    <div class="form-input">
        <input class="form-memo" placeholder= "Type a memo">
    </div>
    <input class="form-submit" type="submit" value="SEND">
</div>

app/views/memos/_memo.html.erb
<div class="memo">
　<div class="upper-memo">
    <div class="memo-user">
    　<!-- 投稿したユーザー名情報を出力する -->
        <%= memo.name %>
    </div>
    <div class="memo-date">
    　<!-- 投稿した時刻を出力する -->
        <%= l memo.user.created_at %>
    </div>
　</div>
　<div class="lower-memo">
    <div class="memo-content">
    　<!-- 投稿したメッセージ内容を記述する -->
        <%= memo.content %>
    </div>
  </div>
</div>

app/views/memos/_right_side_bar.html.erb
<div class="calendar">
    <span class="material-icons">
        navigate_before
    </span>
    <span class="material-icons">
        navigate_next
    </span>
</div>

<div class="schedule">
    <%#= link_to new_room_path do %>
        <span class='material-icons'>add</span>
    <%# end %>
    <span class="material-icons">
        clear
    </span>
</div>

app/views/memos/create.html.erb
$("#memo").html("<%= j(render("memo", memos: @memos)) %>");
$("#content").val("");

app/views/memos/index.html.erb
<div class="header">
    <div class="logo">
        MemoSuke
    </div>

        <%
=begin%>
 <div class="search-bar-contents">
            <form class="search-form" action="#">
                <input class='input-box' placeholder='キーワードから探す'>
                <button class="search-btn">
                    <span class="material-icons">
                        search
                    </span>
                </button>
            </form>
        </div> 
<%
=end%>

    <ul class='user-lists'>
        <%if user_signed_in? %>
            <li >hello. <%= link_to current_user.nickname, "#", class: "user-nickname", id: "link-content"  %></li>
            <li ><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "logout", id: "link-content"  %></li> 
        <% else %>
            <li ><%= link_to 'Log In', new_user_session_path, class: "login", id: "link-content" %></li>
            <li ><%= link_to 'Sign In', new_user_registration_path, class: "sign-up", id: "link-content" %></li>
        <% end %>
    </ul>
</div>

<div class="wrapper">
    <div class="left-side">
        <%= render "left_side_bar" %>
    </div>
    <div class="main-memo">
        <%= render "main_memo" %>
    </div>
    <div class="right-side">
        <%= render "right_side_bar" %>
    </div>
</div>

app/views/rooms/_form.html.erb
    <%= form_with(model: @room, id: "room-form") do |form| %>
        <div  class="form", name="room[user_ids][]">
            <%= form.text_field :name, id: "name" %>
            <%= form.submit '作成', id: "submit" %>
        </div>
    <% end %>

app/views/rooms/_room.html.erb
<%# ルーム作成時の戻り値 %>

<div class="room_area">
    <% @rooms.each do |room| %>
        <div class="rooms">
            <%= link_to room.name, room_memos_path(room), id: "room-name"%>
        </div>
    <% end %>
</div>

app/views/rooms/create.js.erb
$("#room").html("<%= j(render("room", rooms: @rooms)) %>");
$("#name").val("");

app/views/rooms/index.html.erb
<div class="header">
    <div class="logo">
        MemoSuke
    </div>

        <%
=begin%>
 <div class="search-bar-contents">
            <form class="search-form" action="#">
                <input class='input-box' placeholder='キーワードから探す'>
                <button class="search-btn">
                    <span class="material-icons">
                        search
                    </span>
                </button>
            </form>
        </div> 
<%
=end%>

    <%
=begin%>
 <ul class='user-lists'>
        <%if user_signed_in? %>
            <li >hello. <%= link_to current_user.nickname, "#", class: "user-nickname", id: "link-content"  %></li>
            <li ><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "logout", id: "link-content"  %></li> 
        <% else %>
            <li ><%= link_to 'Log In', new_user_session_path, class: "login", id: "link-content" %></li>
            <li ><%= link_to 'Sign In', new_user_registration_path, class: "sign-up", id: "link-content" %></li>
        <% end %>
    </ul>
</div> 
<%
=end%>

<div class="wrapper">
    <div class="left-side">
        <%= render "memos/left_side_bar" %>
    </div>
    <%
=begin%>
 <div class="main-memo">
        <%= render "memos/main_memo" %>
    </div>
    <div class="right-side">
        <%= render "memos/right_side_bar" %>
    </div> 
<%
=end%>
</div>

app/views/rooms/new.html.erb
<div class='memo-room-form'>
  <div class="top-memo-room">
    <div class="room-cancel-btn">
      <%= link_to root_path do %>
        <span class="material-icons", id="clear">
          clear
        </span>
      <% end %>
    </div>
  </div>

  <div class="post-memo">
    <div class="post-logo">
      memosuke
    </div>

    <div class="bottom-section">
      <%=form_with model: @room, local: true do |f|%>
        <div class='chat-room-form__field'>
          <div class='chat-room-form__field--left'>
            <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
          </div>

          <div class='chat-room-form__field--right'>
            <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'ルーム名を入力してください'%>
          </div>
        </div>

        <div class='chat-room-form__field'>
          <div class='chat-room-create'>
            <%= f.submit class: 'chat-room-form__action-btn'%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>